version: '2.1'

services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:5.3.1
    networks:
      es_net:
    ports:
      - "5601:5601"

  elasticsearch1:
    container_name: es1
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    networks:
      es_net:
        aliases:
          - elasticsearch
    mem_limit: 1g
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  elasticsearch2:
    container_name: es2
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    environment:
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    mem_limit: 1g
    networks:
      es_net:
    volumes:
      - esdata2:/usr/share/elasticsearch/data

  elasticsearch3:
    container_name: es3
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    environment:
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    mem_limit: 1g
    networks:
      es_net:
    volumes:
      - esdata3:/usr/share/elasticsearch/data

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:5.3.1
    networks:
      es_net:
    volumes:
        - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    mem_limit: 1g

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local

networks:
  es_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.7.7.0/16
          gateway: 10.7.7.1
