version: '2.1'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.1
    networks:
      es_net:
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    networks:
      es_net:
        aliases:
          - elasticsearch
    mem_limit: 1g
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "xpack.security.enabled=false"
    ports:
      - "9200"
    volumes:
      - /usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:5.3.1
    networks:
      es_net:
        aliases:
          - logstash
    expose:
      - "5000"
      - "5044"
    ports:
      - "5000:5000"
      - "5044"
    volumes:
        - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    mem_limit: 1g
    depends_on:
      - elasticsearch

  httpd:
    image: httpd:alpine
    networks:
      es_net:
    ports:
      - "80"
    logging:
      driver: syslog
      options:
          syslog-address: "tcp://localhost:5000"
    depends_on:
      - logstash

networks:
  es_net:
    driver: bridge
