version: '2.1'

services:

  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.1
    networks:
      es_net:
    ports:
      - "5601:5601"

  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
    networks:
      es_net:
        aliases:
          - elasticsearch
    mem_limit: 1g
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
    environment:
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    mem_limit: 1g
    networks:
      es_net:
    volumes:
      - esdata2:/usr/share/elasticsearch/data


  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
    environment:
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    mem_limit: 1g
    networks:
      es_net:
    volumes:
      - esdata3:/usr/share/elasticsearch/data

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local

networks:
  es_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.7.7.0/16
          gateway: 10.7.7.1
